FROM jenkinsci/blueocean

# ARG ROOT

# # docker run \
# #   -u root \
# #   --name jenkins \
# #   -p 8080:8080 \
# #   -v jenkins-data:/var/jenkins_home \
# #   -v /var/run/docker.sock:/var/run/docker.sock \
# #   -v "$HOME":/home \
# #   jenkinsci/blueocean
