version: "3.2"
services:
  eureka:
    build: ./eureka-server
    ports:
        - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      PORT: 8761
    volumes:
      - ~/.m2:/root/.m2
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      PORT: 8080
      EUREKA_IP: eureka
      EUREKA_PORT: 8761
    volumes:
      - ~/.m2:/root/.m2
  cars:
    build: ./cars
    environment:
      SPRING_PROFILES_ACTIVE: dev
      PORT: 8081
      EUREKA_IP: eureka
      EUREKA_PORT: 8761
    volumes:
      - ~/.m2:/root/.m2

volumes: {}